spring.application.name: urlsln
server.port: ${PORT:8080}

springdoc.swagger-ui.path: /doc

spring:
  data:
    mongodb:
      uri: ${URL_DB:mongodb://localhost:27017/ml-db?retryWrites=true&w=majority}

application.service: urls-ln
application.version: @project.version@
